---
- name: install Jenkins package in Jenkins server
  hosts: Jenkins
  tasks:
   - name: install different packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: openjdk-8-jdk,b: present,c: yes}
      - {a: git,b: present, c: no}
      - {a: maven,b: present, c: yes}
   - name: check if jenkins.war file is present or not
     stat:
      path: /home/ubuntu/jenkins.war
     register: aa
   - name: display above module output
     debug:
      var: aa
   - name: delete if Jenkins.war file is present file
     file:
      name: /home/ubuntu/jenkins.war
      state: absent
     when: aa.stat.exists==true
   - name: download file from Jenkins site
     get_url:
      url: https://get.jenkins.io/war-stable/2.263.4/jenkins.war
      dest: /home/ubuntu
- name: install tomcat9 in servers
  hosts: servers
  tasks:
   - name: install tomcat9 packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tomcat9,b: present,c: yes}
      - {a: tomcat9-admin,b: present,c: yes}
   - name: delete tomcat-users file if it present
     stat:
      path: /etc/tomcat9/tomcat-users.xml
     register: ab
   - name: display above module output
     debug:
      var: ab
   - name: remove if file is present
     file:
      name: /etc/tomcat9/tomcat-users.xml
      state: absent
     when: ab.stat.exists==true
   - name: copy tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9


...
